// @ts-nocheck
// Above is for until when the data given here is not coming from backend
// Next
import Head from "next/head";
import type { NextPage } from "next";

// Components
import FullLayout from "components/layouts/fullLayOut";
import BetList from "components/marketplace";

const MarketplacePage = (): NextPage => {
  return (
    <FullLayout>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BetList />
    </FullLayout>
  );
};

export default MarketplacePage;
